services:
  - name: waymapper-backend
    type: web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT

  - name: waymapper-frontend
    type: web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
    envVars:
      - key: BACKEND_URL
        value: "https://waymapper-backend.onrender.com"